# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Effie Liouta
title: Web Developer
#email: effieliouta@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  e-liouta
instagram_username: effie_lt
linkedin_username: atuoil

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Effie and I'm a Web Developer. As well as web developer I also have experience as a graphic designer. I have worked at a number of companies gaining teamwork skill.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: QA auth
        sub_title: Web Developer
        caption: Sept 2022 - Current
        description: | # this will include new lines to allow paragraphs
            Website Development
            
    # content:
      - layout: left
        title: Plantech.gr
        sub_title: Web Designer & Developer
        caption: May 2019 - September 2022
        description: | # this will include new lines to allow paragraphs
            Responsive Web Design, Website Development (using CMS), SEO, Database Optimization, Site Health - Maintance
            
    # content:
      - layout: left
        title: aLearning.gr
        sub_title: Graphic Designer
        caption: Jul 2020 - Feb 2021
        description: | # this will include new lines to allow paragraphs
            Illustrator for children’s books, Advertisements, Social media posts
            
      #content:
      - layout: left
        title: Click.Solutions
        sub_title: Junior Web Developer
        caption: Jan 2019 - Apr 2019
        description: | # this will include new lines to allow paragraphs
            Development ( Website using CMS ), Copywrite
            
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Patrs
        caption: 2022 - present
        sub_title: MSc, Human Computer Interaction
        description: | # this will include new lines to allow paragraphs
         I just started this program and I very excited
         
      - layout: left
        title: Institute of Vocational Training Delta 360
        caption: 2018 - 2020
        sub_title: Diploma of Graphic Design for print and electronic media
        description: | # this will include new lines to allow paragraphs
         During this programm at the Institute od Vocational Delta 360 I developed skills such as drawing, aesthetics, color theory, branding, motion graphics, web design and graphic design. Some of the tools I used are Adobe Photoshop, Adobe Illustrator, Adobe InDesign, Adobe AfterEffects, Adobe Dreamweaver, Adobe Premier, Figma... 
    
      - layout: left
        title: University Of Ioannina
        caption: 2012 - 2018
        sub_title: BSc, Computer Science
        description: | # this will include new lines to allow paragraphs
         During my studies at the department of computer scence at the Univeristy of Ioannina I had the opportunity to learn about many fields. My favourites were Computer Graphics, Multimedia and Operating Systems.
    
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Web some of my other interests and hobbies are dancing, hiking, painting, snorkeling, traveling and educating myself and my friends about a more sustainable, consius and ethical lifestyle.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
