# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Effie Liouta
title: Web Developer
#email: effieliouta@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  e-liouta
instagram_username: effie_lt
linkedin_username: atuoil


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
 
  - title: Experience # Title for the section
  
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: QA Auth 
        sub_title: Web Developer
        caption: September 2022 - Current
        description: | # this will include new lines to allow paragraphs
            Web Development

    #layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Plantech
        sub_title: Web Designer & Developer
        caption: May 2019 - September 2022
        description: | # this will include new lines to allow paragraphs
            Responsive Web Design, Website Development (using CMS), SEO, Database Optimization, Site-Health Maintance.
       
     #layout: list # Type of content section (list/text)
     content:     
       - layout: left
        title: aLearning.gr
        sub_title: Illustrator
        caption: July 2020 - February 2021
        description: | # this will include new lines to allow paragraphs
            Illustration for children's books, Advertisements, Social Media Posts.
            
     #layout: list # Type of content section (list/text)
     content:     
       - layout: left
        title: Click Solutions
        sub_title: Junior Web Developer
        caption: January 2019 - April 2019
        description: | # this will include new lines to allow paragraphs
            Web Development, Copywrite.
            
   

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Patras
        caption: 2022 - Current
        sub_title: MSc, Human - Computer Interaction
        description: | # this will include new lines to allow paragraphs
          I just started this Master Program and I am very excited!
          
     content:
      - layout: left
        title: Vocational Training Institute Delta 360
        caption: 2018 - 2020
        sub_title: Diploma of Print & Electronic Media Graphic Design
        description: | # this will include new lines to allow paragraphs
          During this programm I developed skills like drawing, color theory, aesthetics, branding, graphic design, web design and motion graphics.
          
      content:
      - layout: left
        title: University Of Ioannina
        caption: 2012 - 2018
        sub_title: ΒΑ, Comptuter Science
        description: | # this will include new lines to allow paragraphs
          During my studies at the department of Computer Science at the University of Ioannina, I had the opportunity to learn about many different fields and programming languages. My favourite were Computer Graphics, Μultimedia and Operating Systems.
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Web Development some of my other interests and hobbies are dancing, gardening, hiking, snorkeling, painting and educating myself and my friends about a more sustainable, conscious, and ethical lifestyle.

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
